# Generated by Django 4.1.3 on 2022-11-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answer', models.TextField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('right_answer', models.TextField(max_length=200)),
                ('question', models.TextField(max_length=200)),
                ('response', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('did_you_know', models.TextField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.event')),
            ],
        ),
    ]
